### ISSUE TITLE
Tomcat configured to write to a non-writable location on Tiny stack

### ISSUE THREAD

**Issue by dmikusa** [paketo-buildpacks/apache-tomcat#279]
## Expected Behavior

If software needs to write to disk at runtime, it should be writing to `/tmp` (a convention Paketo is following).

## Current Behavior

The [Tomcat start command on Tiny](https://github.com/paketo-buildpacks/apache-tomcat/blob/main/tomcat/build.go#L207) that we generate tells Tomcat to write temp files to the Tomcat base layer, which may not always be writable at runtime.

## Possible Solution

1. Change it to write to `/tmp` by default.
2. Look to see if `TMPDIR` env variable is set, which means a user has indicated temp files should be somewhere else.
3. Look at `JAVA_TOOL_OPTIONS` to see if a `-Djava.io.tmpdir` has been set, if set then buildpack should back off.

If a user changes the location of `/tmp` we just assume it will be writable at runtime.

## Steps to Reproduce
n/a

## Motivations

1. Support for Tiny + Jammy.
2. Support for running as different runtime user

**Comment by loewenstein** [comment]
@dmikusa should the numbering be changed? I.e. 
1. Check `TMPDIR` environment variable and write there
2. Right to `/tmp` if `TMPDIR` is not set
3. Set `java.io.tmpdir` to `TMPDIR` (or `/tmp` If env is not set)
