### ISSUE TITLE
Artifacts downloaded from repo.spring.io will be unavailable after permissions changes

### ISSUE THREAD

**Issue by scottfrederick** [paketo-buildpacks/apache-tomcat#295]
This buildpack [downloads several artifacts](https://github.com/paketo-buildpacks/apache-tomcat/blob/main/buildpack.toml#L139-L175) from `repo.spring.io`. Once the [permissions changes](https://spring.io/blog/2022/12/14/notice-of-permissions-changes-to-repo-spring-io-january-2023) to this repository are made, these downloads will fail.

**Comment by dmikusa** [comment]
For now, this is just temporary. We're should be done with the brownout for today so builds should be working again. I don't think we have a way to bypass these downloads. We are working on moving this resource over to Maven Central though, and we hope to have that done before the next brownout (Jan 12th). 

There is a caveat though. We can **only** change that in new buildpack releases. When that fix is released everyone will need to update to the latest buildpack to pick up that change.

I'll keep this issue open & we'll post a note here when we have cut a new buildpack release that pulls from Maven Central.

Thanks for being patient through this. It’s hard on everyone when a major infrastructure change happens.
