### ISSUE TITLE
Multi-WAR support for two additional use cases

### ISSUE THREAD

**Issue by dmikusa** [paketo-buildpacks/apache-tomcat#426]
## Describe the Enhancement

In #402, we merged in multi-war support when building from source. This feature request is to add support for using precompiled assets.

Both of the following cases should work when this feature request is complete:

- Precompiled assets path pointing to a directory with multiple WAR files in it, buildpacks see the same
- Precompiled assets path pointing to a directory with a single WAR file in it, buildpacks will see the WAR file not an exploded WAR.

## Motivation

Support multi-wars when building assets outside of buildpacks.

## Steps to Test

1. `mkdir single-war`
2. `./mvnw package` one of your apps or a Paketo sample app
3. Move that into the `single-war/` directory
4. `pack build -p ./single-war/` and include all the other options for pack build you'd normally use

Pack will use the directory as the application contents, so inside the container buildpacks will see the contents of that folder as `/workspace`.

1. `mkdir multi-war`
2. `./mvnw package` one of your apps or a Paketo sample app
3. Copy that into the `multi-war/` directory twice with different names.
4. `pack build -p ./multi-war/` and include all the other options for pack build you'd normally use

Pack will use the directory as the application contents, so inside the container buildpacks will see the contents of that folder as `/workspace`.

**Comment by PG2000** [comment]
+1

**Comment by sagaert** [comment]
+1

**Comment by dmikusa** [comment]
Resolved with #500
