### ISSUE TITLE
We should remove outdated versions of Apache Tomcat

### ISSUE THREAD

**Issue by loewenstein** [paketo-buildpacks/apache-tomcat#443]
Looking at https://endoflife.date/tomcat
- the `10.0` line has reached EOL already well over a year ago
- the `8.5` line will reach EOL in about 5 days

We should likely remove both very soon, maybe use `deprecation-date` as a last minute warning shot. But I am honestly not sure if this is worth the effort.

Not sure how to make sure we don't miss this for `9.x` and `10.1` when they get an assigned EOL. [This post](https://lists.apache.org/thread/qlzpscgoqct9wspkj5qjkm34s66jswj0) sounds like `9.x` will be continued as `9.10.x` and later `9.11.x` to keep JavaEE supported. The `10.1` EOL will depend on Tomcat 12 and 13 development (once that is at all started) and JakartaEE specification work. Maybe all we got would be some kind of yearly or half-yearly reminder.

**Comment by dmikusa** [comment]
+1 for removing 10.0
+1 for removing 8.5 *after* the final release

If someone needs to continue using one of those versions, they can pin the buildpack version or they can repackage with their own metadata in buildpack.toml.
